config/config.json, migrations/20240916091032-create-user.js, models/index.js, models/user.js, package-lock.json, package.json, seeders/20240916091547-demo-user.js
This pull request sets up Sequelize as the ORM for the project and configures the database connection.
- Initialized Sequelize and created the required project structure (`models`, `migrations`, `seeders`, etc.)
- Configured database connection settings in `config/config.json`
- Added a User model as an example with the corresponding migration file
- Installed necessary dependencies (`sequelize`, `sequelize-cli`, and the appropriate database driver)
- Make sure to create a local `.env` file to provide the correct database credentials for local development.
- You can run migrations using `npx sequelize-cli db:migrate` and seed the database with `npx sequelize-cli db:seed:all`.
- Create additional models as needed.
- Implement database operations in API routes.
=> Setup Sequelize with database configuration

src/app/(auth)/loading.tsx, src/app/(auth)/login/page.tsx
This PR adds a loading spinner to the submit button on the login page to improve user experience during the authentication process. 
- Integrated a loading state with a spinner that activates when the login request is in progress.
- Disabled the submit button and added an opacity change while loading to prevent multiple submissions.
- Ensured the spinner displays correctly with animation and user-friendly text ("Logging in...").
This enhancement improves the UI feedback, making the app more responsive to user actions during login.
=> Add spinner to submit button during loading state

src/app/dashboard/layout.tsx
This PR addresses UI responsiveness issues across the User Management page and dashboard navigation. Key changes include:
- Implemented mobile-first responsive design for the sidebar, ensuring it remains hidden on larger screens and functions with a toggle on smaller screens.
- Added accessibility features and improved usability by including icons and clear navigation actions.
- Replaced "Loading..." text with skeleton loaders for a better loading experience (install 'react-loading-skeleton' package for this functionality).
- Integrated confirmation modals for deletion actions, preventing accidental data loss.
- Refined toast notifications for successful or failed actions, providing clear user feedback.
- Cleaned up code and optimized imports for better maintainability.
These changes …
=> Fix UI Responsiveness and Improve User Management Experience

.github/workflows/deploy.yml, Dockerfile
This pull request merges the latest changes from the `main` branch into the `development` branch following the fix for the Docker Hub authentication issue. The fix ensures that both the build and deploy jobs in the GitHub Actions workflow properly authenticate to Docker Hub when interacting with a private repository.
- Added a Docker login step in the `deploy` job to allow access to the private Docker Hub repository during the pull phase.
- Ensured consistent repository naming and image tagging throughout the workflow.
This merge will synchronize the `development` branch with the recent fixes and improvements on the `main` branch, keeping both branches aligned.
=> Merge main into development after fix for private Docker Hub repository access

.github/workflows/deploy.yml
This pull request adds support for running database migrations and seeders as part of the deployment process for the application.
- Updated the GitHub Actions workflow to include steps for running database migrations (`npm run migrate`) and seeders (`npm run seed`) after deploying the Docker container.
- Ensured that the database schema is updated and initial seed data is populated automatically as part of the deployment process.
- These changes ensure that each deployment applies any new migrations and seed data, keeping the database in sync with the latest application code.
With this update, the deployment workflow is now fully automated, handling both code updates and database schema updates.
=> Add database migration and seeder steps to deployment workflow

.github/workflows/deploy.yml, lib/axios.ts
This pull request merges recent changes from the main branch into the development branch. The following updates are included:
- **CORS Configuration:** Resolved issues with Cross-Origin Resource Sharing (CORS) that were preventing access to the authentication API from the frontend.
- **API Endpoint Update:** Updated the API endpoint to point to the correct production URL for authentication.
- **Backend Accessibility:** Ensured the backend server is reachable and configured to respond correctly to requests from the frontend.
=> Merge Changes from Main to Development: Fix CORS and Update API Endpoint

.gitignore
This PR adds and configures the following environment files to streamline local development and production builds:
1. `.env.local` – For local development. It sets up environment variables such as the base URL for the API when running the app locally.
2. `.env.production` – For production deployment. This file includes production-specific environment variables like the production API URL.
3. `.env.production.local` – For testing production builds locally. This file overrides `.env.production` during local testing of production builds to use local resources (e.g., API base URL).
Changes in this PR ensure that:
- Developers can seamlessly switch between environments without modifying `.env` files.
- Local testing of production builds works correctly with the appropriate local API URL. …
=> Add environment configuration for local and production builds

database/migrations/20241018090913-add-intakeYear-to-intakes.ts, src/app/api/intakes/[intakeId]/route.ts, src/app/api/intakes/route.ts, src/app/dashboard/intakes/[intakeId]/page.tsx, src/app/dashboard/intakes/create/page.tsx, src/app/dashboard/intakes/edit/[intakeId]/page.tsx, src/app/dashboard/intakes/page.tsx, src/app/dashboard/layout.tsx, src/components/Forms.tsx, src/db/models/Intake.ts, src/types/index.ts
- Added support for creating, reading, updating, and deleting Intakes
- Included fields for intake name and date to store
- Updated migration and model to support new columns for
- Implemented API routes to handle CRUD operations for Intakes
=> feature: add CRUD functionality for Intakes with date and name fields

src/app/api/modules/[moduleId]/route.ts, src/app/api/modules/route.ts, src/app/dashboard/layout.tsx, src/app/dashboard/modules/create/page.tsx, src/app/dashboard/modules/edit/[moduleId]/page.tsx, src/app/dashboard/modules/page.tsx, src/app/dashboard/page.tsx, src/components/Forms.tsx, src/types/index.ts
This pull request introduces full CRUD (Create, Read, Update, Delete) functionality for managing modules within the application. The following key features have been implemented:
- **Create Module**: A form to allow users to create new modules with `moduleName` and `courseId`.
- **Read Modules**: Fetch and display a list of modules from the backend, with search functionality.
- **Update Module**: Edit module details, such as `moduleName`, and update the module in the database.
- **Delete Module**: Delete an existing module from the system.
- **Form Validation**: Basic client-side validation for creating and updating modules.
- **Notifications**: Toast notifications for success and error handling during CRUD operations.
This update enhances the admin dashboard with robust module management …
=> Add Module CRUD Functionality

src/app/dashboard/@analytics/page.tsx, src/app/dashboard/@overview/page.tsx, src/app/dashboard/@reports/page.tsx, src/app/dashboard/layout.tsx, src/app/dashboard/page.tsx
This PR adds professional card components for Overview, Reports, and Analytics sections in the Dashboard. The content for these sections is now rendered using a responsive grid layout that adjusts for various screen sizes. 
- Added individual cards for Overview, Reports, and Analytics in the `layout.tsx`.
- Implemented a responsive grid using Tailwind CSS for better display on small, medium, and large screens.
- Applied consistent spacing and styling across the dashboard sections to enhance readability and visual appeal.
- Ensured proper rendering on both view and create modes for other components within the dashboard.
- Used a `grid-cols-1`, `md:grid-cols-2`, and `lg:grid-cols-3` layout to ensure responsiveness across different devices.
- Utilized Tailwind utility classes for layout …
=> Add Professional Cards for Overview, Reports, and Analytics to Dashboard Layout

src/app/api/modules/[moduleId]/route.ts, src/app/api/modules/route.ts, src/app/dashboard/modules/create/page.tsx, src/app/dashboard/modules/edit/[moduleId]/page.tsx, src/app/dashboard/modules/page.tsx, src/components/Forms.tsx, src/db/models/Module.ts, src/types/index.ts
Fix: Dynamic course module functionality and bug resolution
- Resolved issues with dynamic loading of course modules to ensure seamless user experience.
- Fixed bugs causing incorrect data display and interactions within the course module.
- Enhanced performance of dynamic components to improve responsiveness.
- Updated relevant tests to cover the new behavior and ensure functionality is maintained.
- Reviewed code for potential edge cases that may affect module loading and user interactions.
This fix improves the reliability and performance of the dynamic course module feature.
=> Fix: Dynamic course module functionality and bug resolution

src/app/api/class-times/[classTimesId]/route.ts, src/app/api/class-times/route.ts, src/app/dashboard/class-times/[classTimesId]/page.tsx, src/app/dashboard/class-times/create/page.tsx, src/app/dashboard/class-times/edit/[classTimesId]/page.tsx, src/app/dashboard/class-times/page.tsx, src/app/dashboard/layout.tsx, src/components/Forms.tsx, src/db/models/ClassTime.ts, src/types/index.ts
Add CRUD functionality for class times in Next.js app
- Implemented Create, Read, Update, and Delete operations for class times.
- Utilized Next.js API routes to handle server-side functionality.
- Added frontend components/pages for managing class times.
- Integrated form validation and error handling for each CRUD operation.
- Optimized data fetching using Next.js server-side capabilities (e.g., getServerSideProps or API routes).
This feature enables full class times management with a Next.js-based solution.
=> Add CRUD functionality for class times

src/app/dashboard/@analytics/default.tsx, src/app/dashboard/@overview/default.tsx, src/app/dashboard/@reports/default.tsx, src/app/dashboard/default.tsx, src/app/default.tsx
Description:
This PR addresses an issue where using slots caused layout inconsistencies, particularly on page refresh. To resolve this, default.tsx has been introduced as a default layout component, ensuring a stable and consistent rendering experience across the application.
Changes Made:
Added default.tsx to standardize layout rendering
Updated component references to utilize default.tsx as the default layout wrapper
Impact:
This change will prevent layout shifts caused by missing slot content during page reloads, improving user experience and UI consistency.
Testing:
Verified layout stability across multiple refresh scenarios
Confirmed no impact on existing functionality and slot content display
=> Fix layout inconsistency due to slot usage by adding default.tsx for stable rendering on refresh

src/app/api/feedback/[feedbackId]/route.ts, src/app/api/feedback/route.ts, src/app/dashboard/feedback/create/page.tsx, src/app/dashboard/feedback/edit/[feedbackId]/page.tsx, src/app/dashboard/feedback/page.tsx
Description:
This update introduces two major features:
Multi-Step Form for Job Creation
Streamlines job creation by separating input into two steps:
Step 1: Job details (position, department, etc.)
Step 2: Schedule and additional details
Feedback Question Editing
Enables users to edit feedback questions within existing feedback entries.
Testing:
Tested form flow and editing functionality to ensure seamless user experience and data accuracy.
=> Add Multi-Step Job Creation and Feedback Question Editing

src/app/dashboard/feedback/page.tsx, src/components/Tables.tsx
This PR introduces enhancements to the Table component to improve user experience by allowing users to easily copy student tokens. A clipboard icon is now displayed next to the student token when applicable.
Changes Made:
Feature Addition: Implemented a button with a clipboard icon that enables users to copy the student token directly from the table.
Conditional Rendering: The button is displayed only if the column accessor is of type string and corresponds specifically to studentToken.
Type Safety: Updated type definitions in the Table component to ensure better type safety and maintainability.
Benefits:
User Experience: Simplifies the process of copying student tokens, making it more intuitive for users.
Code Quality: Enhancements follow coding best practices, improving the overall …
=> Enhance Table Component for Copying Student Tokens

src/app/dashboard/class-times/page.tsx, src/app/dashboard/courses/page.tsx, src/app/dashboard/feedback-questions/page.tsx, src/app/dashboard/feedback/page.tsx, src/app/dashboard/intakes/page.tsx, src/app/dashboard/loading.tsx, src/app/dashboard/modules/page.tsx, src/app/dashboard/permissions/page.tsx, src/app/dashboard/roles/page.tsx, src/app/dashboard/trainers/page.tsx, src/app/dashboard/users/page.tsx, src/app/loading.tsx, src/app/page.tsx, src/app/studets-feedback/[feedbackId]/page.tsx
**Summary**  
This PR introduces a loading spinner to the feedback page, providing a professional and responsive loading indicator when fetching data. The standalone `Loading` component is imported and utilized, replacing the previous inline loading condition to improve component structure and readability.
**Changes**  
- Created a reusable `Loading` component (`src/app/loading.tsx`) with Tailwind styling for a modern spinner effect.
- Updated the feedback page to use `<Loading />` instead of an inline `if (loading)` condition.
- Improved UI consistency by centralizing loading display logic in one component.
**Testing**  
- Verified loading spinner displays while data is being fetched.
- Ensured the feedback page renders correctly once data loading completes.
**Notes**  
This update …
=> Add Loading Spinner Component to Feedback Page for Enhanced UX

lib/pdfGenerator.ts, package-lock.json, package.json, src/app/api/feedback-questions/[questionId]/route.ts, src/app/api/feedback-reports/[feedbackReportId]/route.ts, src/app/api/feedback-reports/route.ts, src/app/dashboard/feedback-reports/[feedbackId]/page.tsx, src/app/dashboard/feedback-reports/page.tsx, src/app/dashboard/layout.tsx, src/components/Tables.tsx, src/db/models/Feedback.ts, src/db/models/FeedbackAnswer.ts, src/db/models/FeedbackQuestion.ts
This PR implements conditional feedback report generation, enabling users to view and export reports in PDF format only when feedback data is available. Enhancements include UI consistency, conditional rendering, and improved PDF layout for user readability.
Key Changes
PDF Generation:
Added downloadPDF function to dynamically generate PDF reports with relevant feedback details, including Trainer, Course, Module, Intake, and Class Time.
Structured PDF output with headers, questions, answers, and response percentages for organized layout.
Introduced page break handling to prevent overflow, improving readability in multi-page PDFs.
Conditional UI Rendering:
Displayed a fallback message if no feedback data is found, removing buttons in such cases.
Wrapped Download PDF and Send Feedback …
=> Add Conditional Feedback Report Generation with PDF Export Functionality

.github/workflows/deploy.yml
This pull request removes the deploy task from the CI/CD pipeline. The deployment process has been revised, and this task is no longer necessary within the current workflow.
- Removed the deploy task from the pipeline configuration.
- Updated related documentation to reflect the changes in the deployment process.
- This change simplifies the CI/CD workflow by eliminating redundant steps.
- Future deployments will now be managed through the new deployment strategy outlined in the updated documentation.
=> Remove Deploy Task from CI/CD Pipeline

src/app/dashboard/layout.tsx
- **Navbar Responsiveness**: Fixed navbar color inconsistency on smaller screens to ensure uniformity across all screen sizes.
- **Hamburger Menu**: Adjusted hamburger menu color for consistency with the navbar theme.
- Ensured that the color styling for the navbar is managed consistently using CSS variables or responsive design techniques.
- 
- Please review the changes for responsiveness, consistency, and adherence to the design guidelines. Let me know if any adjustments are needed or if further testing is required.
=> Fix navbar responsiveness and styling

lib/axios.ts
=> Fix: base-url

lib/axios.ts, src/app/dashboard/layout.tsx
=> Development -Main

database/config/config.mjs
=> Fix: Logging

lib/axios.ts
##Description
Fixed base url to https
=> Fix: base url

database/config/config.mjs, lib/axios.ts
=> Fix base url

src/app/api/feedback-reports/[feedbackReportId]/route.ts, src/app/dashboard/feedback-questions/create/page.tsx, src/app/dashboard/feedback-reports/[feedbackId]/page.tsx
PR Description:
Overview:
This PR introduces the ability to view descriptions provided by students for specific answer options in the feedback PDF report. It ensures that the generated report reflects the context behind student responses, improving the transparency and usefulness of feedback.
Key Changes:
Description Handling:
Extracts and displays descriptions associated with answer options for both closed-ended and open-ended questions.
Descriptions are shown directly beneath the answer options, marked with a clear red label for identification.
Text Wrapping:
Implemented automatic text wrapping for long descriptions, ensuring the content fits within the specified page width without overflow.
UI/UX Improvements:
Adjusted layout to maintain readability and structure, with proper spacing …
=> fix/added a way to view the descriptions made by students in a specified answerOption in the feedback PDF report

src/app/(auth)/forgot-password/page.tsx, src/app/(auth)/reset-password/page.tsx, src/app/dashboard/class-times/edit/[classTimesId]/page.tsx, src/app/dashboard/class-times/page.tsx, src/app/dashboard/courses/edit/[courseId]/page.tsx, src/app/dashboard/courses/page.tsx, src/app/dashboard/default.tsx, src/app/dashboard/feedback-questions/edit/[questionId]/page.tsx, src/app/dashboard/feedback-questions/page.tsx, src/app/dashboard/feedback-reports/[feedbackId]/page.tsx, src/app/dashboard/feedback/edit/[feedbackId]/page.tsx, src/app/dashboard/feedback/page.tsx, src/app/dashboard/intakes/edit/[intakeId]/page.tsx, src/app/dashboard/intakes/page.tsx, src/app/dashboard/layout.tsx, src/app/dashboard/modules/edit/[moduleId]/page.tsx, src/app/dashboard/modules/page.tsx, src/app/dashboard/permissions/edit/[permissionId]/page.tsx, src/app/dashboard/permissions/page.tsx, src/app/dashboard/roles/edit/[roleId]/page.tsx, src/app/dashboard/roles/page.tsx, src/app/dashboard/trainers/edit/[trainerId]/page.tsx, src/app/dashboard/trainers/page.tsx, src/app/dashboard/users/edit/[userId]/page.tsx, src/app/dashboard/users/page.tsx, src/app/page.tsx, src/app/studets-feedback/[feedbackId]/page.tsx, src/db/db_connection.ts
##Description
Resolve build issues with Sequelize and TypeScript.
=> Resolve build issues with Sequelize and TypeScript.

src/app/dashboard/feedback-reports/[feedbackId]/page.tsx
=> resolve build issues

database/migrations/20241118084956-add-token-start-time-to-feedback.ts, src/app/api/feedback/[feedbackId]/route.ts, src/app/api/feedback/route.ts, src/app/api/feedback/token/[feedbackToken]/route.ts, src/app/dashboard/feedback/create/page.tsx, src/app/dashboard/feedback/edit/[feedbackId]/page.tsx, src/app/dashboard/feedback/page.tsx, src/app/dashboard/roles/edit/[roleId]/page.tsx, src/app/dashboard/user-profile/[userId]/page.tsx, src/components/Forms.tsx, src/db/models/Feedback.ts, src/types/index.ts
This PR introduces the following changes:
Admin Token Activation Time Feature:
Added functionality for administrators to set the start and expiration times for feedback tokens.
Ensures tokens are active only within the specified timeframe, improving control over token validity.
Enhanced Table Component:
Modified the table component to handle and display two distinct time inputs: Token Start Time and Token Expiration Time.
Improved readability and usability for managing token schedules.
Changes Made
Updated the Feedback edit/create forms to include fields for:
Token Start Time
Token Expiration Time
Modified the backend to accept and validate the token timing parameters.
Enhanced the table component to reflect the two separate time fields, ensuring accurate representation.
Screenshots
Form …
=> Added Admin Token Activation Time Feature and Table Component Enhancements

database/migrations/20241129081502-update-feedback-table.ts, src/db/models/Feedback.ts, src/db/models/TrainerCourses.ts
=> Fix: Case issues resolved

package.json
=> Fix: migrate one

src/app/api/feedback/[feedbackId]/route.ts, src/app/dashboard/feedback/edit/[feedbackId]/page.tsx, src/app/dashboard/user-profile/[userId]/page.tsx, src/components/Forms.tsx
- Resolved an issue with feedback error messages.
- Added validation to prevent accepting sam123 as the old password during profile updates.
#Fix Feedback Error and Enhance Profile Update Validation
This PR addresses the following updates:
- Fixed an issue with feedback error messages for a better user experience.
- Enhanced validation logic to disallow "sam123" as the old password during profile updates.
1. **Feedback Error Fix**: Resolved incorrect or missing error messages in the feedback mechanism.
2. **Profile Validation Update**: Added a check to ensure "sam123" cannot be accepted as the old password.
- Verified feedback error messages display correctly in various scenarios.
- Tested the profile update flow to confirm validation works as expected.
These changes improve the …
=> Fix:feedback error and profile update validation

src/app/(auth)/reset-password/page.tsx, src/app/api/users/route.ts, src/app/dashboard/user-profile/[userId]/page.tsx, src/components/Forms.tsx
This pull request updates the password input handling to enhance validation and user experience.
1. **Regex Update**: Adjusted the password regex to enforce stronger validation:
- Password must include at least one lowercase letter, one uppercase letter, one digit, and one special character from the set `@$!%*?&`.
- Minimum length of 8 characters.
- Spaces and disallowed characters (e.g., `.`, `*`, `/`, `\`) are prohibited.
2. **Input Type**: Ensured the password input field is of type `password` for secure input.
- Users are now required to follow updated password rules when creating or updating passwords.
- Provides better security and compliance with strong password policies.
- Tested various password inputs to confirm the regex works as expected.
- Validated input type functionality …
=> Fix Password Input Type and Regex Validation

src/app/api/feedback/route.ts, src/app/dashboard/@analytics/default.tsx, src/app/dashboard/feedback/page.tsx, src/components/Tables.tsx
This update introduces a way to determine and display the status of a token (active, expired, or pending) based on the current time and the token's intended start time. The token status is automatically calculated and rendered, providing users with immediate feedback on the validity of their token.
- **Token Status Logic**: A method to calculate whether the token is `active`, `expired`, or `pending`, based on its start and expiry times.
- **Active**: The token is currently valid and can be used.
- **Expired**: The token has passed its expiration time.
- **Pending**: The token has a start time in the future and is not yet valid.
- **UI Update**: The token status is displayed in the table for each token, making it easy for users to understand the current validity of the token at a glance.
- …
=> ### Feature: Add Token Status Based on Expiry Time

src/app/api/feedback-questions/[questionId]/route.ts, src/app/dashboard/feedback-questions/create/page.tsx, src/app/dashboard/feedback-questions/edit/[questionId]/page.tsx, src/app/student-feedback/[feedbackId]/page.tsx, src/components/Tables.tsx
**Changes Included:**
1. **Dynamic Rating Descriptions:**
- The description for ratings now dynamically updates based on the rating selected, even if the user previously entered text and decides to change the rating.
2. **Feedback Question Fixes:**
- Resolved issues with editing feedback questions, particularly related to required fields.
3. **Loading State for Feedback Creation:**
- Added a loading state when creating new feedback questions to improve user experience.
**Why This PR?**
These fixes ensure smoother interactions with ratings and feedback forms, reducing confusion and enhancing usability.
✅ **Ready for Review!**
=> Pull Request: Fix Rating Description Reset, Required Field Editing, and Add Loading State

.github/workflows/deploy.yml
##Description
-- Fix Logout Redirection to Ensure Proper Navigation
=> Fix Logout Redirection to Ensure Proper Navigation
